### PR TITLE
Update registration tutorial

### PR DESCRIPTION
**Pull request by sacha-l**
Suggestions to update the tutorial for registering a community on Gesell testnet.

For some reason I got an error when trying to complete the final steps:

```bash
 gesell new-community specfile.json 5D4fwokdcKUePqNSGvs9DBkbRycYc6VoDN7spjFv6L6u1HAz
error: error: Found argument '5D4fwokdcKUePqNSGvs9DBkbRycYc6VoDN7spjFv6L6u1HAz' which wasn't expected, or isn't valid in this context
```

I also tried doing this through Polkadot JS Apps UI and got a `BadOrigin` error. Haven't gone too far into trying to understand what's causing this but I suspect it's something in how the runtime expects the `specfile.json` or perhaps the account needs some minimal balance that the faucet is not providing?

Couple of things I'd like to put in before this gets merged:

- [ ] What's next: let's point users to what they should look into after registration.
- [ ] Link or explanation as to what the CID is / how to use it

Other nit picks that could make the experience much better in my opinion:
- [x] The CLI commands for what was `nctr list-communities` is very messy, what's a trick to display just what we want from the RPC return?
- [ ] The new account command is not so user friendly because it just creates artifacts of the seed phrases inside the node project.  Can you modify the CLI tool to also output the corresponding address in the keystore directory?

Hope this write-up helps other users!

### CODE REVIEW

**Comment by brenzi** [comment]
Thanks for these hints! Indeed, our tutorial is outdated since we had to do a few mods for mainnet.

Currently, only the association can register new communities. We can fix that for Testnet Gesell with: https://github.com/encointer/pallets/issues/251

**Comment by brenzi** [comment]
regarding `list-communities`. I don't understand what's messy about it. can you explain @sacha-l ?
```
./encointer-client-notee -u wss://gesell.encointer.org -p 443 list-communities
number of communities:  5
e5dvt5mjcem: bot-tugs locations: 9
u0qj94fxxJ6: EdisonPaula locations: 3
srcq45PYNyD: Adriana locations: 5
u33e0719fDB: Decoded Berlin locations: 3
69y7j4ZEXmy: Decoded Buenos Aires locations: 8
```
The tutorial actually features an example with the old hash-based cid, which now looks more concise. We should change thjat in the tutorial

**Comment by brenzi** [comment]
regarding `new-account`. thats most likely a won't fix for us and should be solved upstream. But they idea was lurking around my head since 2019 as I just realize ;-)
https://github.com/scs/substrate-api-client/issues/266

**Comment by sacha-l** [comment]
> 

Oh that's weird, I no longer get the same result (before I was getting a whole bunch of state query results from the json RPC). I can confirm that it displays nicely now:

```bash
> gesell list-communities
number of communities:  5
e5dvt5mjcem: bot-tugs locations: 9
u0qj94fxxJ6: EdisonPaula locations: 3
srcq45PYNyD: Adriana locations: 5
u33e0719fDB: Decoded Berlin locations: 3
69y7j4ZEXmy: Decoded Buenos Aires locations: 8
```

**Comment by sacha-l** [comment]
>  What's next: let's point users to what they should look into after registration.
 Link or explanation as to what the CID is / how to use it

On these two TODOs could you point me to information about what you'd add?

**Comment by brenzi** [comment]
WIP: https://github.com/encointer/book/pull/7

**Comment by brenzi** [comment]
I have written up some up to date content in https://github.com/encointer/book/pull/7. Please rebase and check if you can use it or if you have further feedback

**Comment by sacha-l** [comment]
Looks like we can close this and I'll follow up with a review of your updates. Cheers!

**Pull request closed without merging**
