### PR TITLE
update tutorials to v0.4.0. should change whole tutorial story

### PR DESCRIPTION
**Pull request by brenzi**

### CODE REVIEW

**Comment by brenzi** [comment]
@anizeani as we now have inverse meetup logic, the tutorials are out of date. from the changes in the bot-community script you should be able to derive what needs to be changed in the tutorial
so it's not only python instead of bash, it's also about sending other's attestations istead of own

**Comment by brenzi** [comment]
@anizeani what is the status?

**Comment by anizeani** [comment]
My changes are for now in the branch:
https://github.com/encointer/book/commits/TutorialPythonInsteadOfBash
Do you want to review?

**Comment by brenzi** [comment]
yes, please merge your changes into this PR so I can comment here

**Comment by brenzi** [comment]
is this ready for review?

**Comment by anizeani** [comment]
I want to make some minor changes until comming monday.

**Comment by anizeani** [comment]
now you can review

**Comment by brenzi** [comment]
The following is outdated. 
https://github.com/encointer/book/blob/f497c72804c7f525ea768c5dbc04a6bd87321610/src/testnet-gesell-tutorial.md?plain=1#L13-L213

I suggest to not just fix it as it is a mostly boring tutorial

This tutorial should be re-purposed to "how to bootstrap an encointer community"

1. create bootstrapper accounts
2. manually compose a community spec json file with the help of geojson.io
3. register community

**Comment by anizeani** [comment]
I have pushed a new version. I explain the functionality of the python script in detail. 
Nevertheless, I think the Bash tutorial is still helpfull to understand many basic functionalities which are wrapped in the pyhton client. I therefore splittet the tutorial into Bootstrapping a comunity automated/manually

**Comment by brenzi** [comment]
I don't like the structure yet. You start with Gesell -> Tutorial, but then you begin with explaining  a local test. Only when scrolling down you see the instructions to register a community on Gesell.

It should be clear from the TOC what happens on Gesell or Locally

**Comment by brenzi** [comment]
@anizeani You're linking to a file `how-to-register-an-encointer-community-manually` which isn't added to git. Does it exist? If yes, please commit it

**Pull request merged**
